Feature/search setting
anvie/lamdam pull request #2
Opened 2023-10-03 05:21 UTC by binsarjr

2023-10-04 00:34 UTC, anvie requested changes
tolong dibenerin dulu indentasinya

2023-10-04 05:06 UTC, binsarjr commented on .editorconfig
Karena beberapa file  saya masih melihat ada yang indent space 2 dan 4. jadi saya tambahkan ini untuk fix  konfigurasi indentnya.nanti setiap save akan otomatis menjadi indent space 4

2023-10-05 15:56 UTC, anvie commented on .editorconfig
ini pake editor apa?

2023-10-05 16:06 UTC, merged

2023-10-05 16:07 UTC, binsarjr commented on .editorconfig
untuk vscode pak